version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - URL=http://localhost:5000
      - FLAG=flag{cookies_are_tasty}

volumes:
  db_data: